### PR TITLE
fix: cells can be scaled without restarting the entire set

### LINKED ISSUE #981: After helm upgrade to scale diego cell count from 3 to 4, 2 out of 3 diego-cell pods gets restarted
**Describe the bug**
When I use `helm upgrade` to scale up the diego cell count for 3 to 4. diego-cell-2 and diego-cell-1 get restarted consecutively, once new diego-cell-3 is up. 
diego-cell-0 never gets restarted

It takes 19 min approx for all pods to get in `running` state

**To Reproduce**

- HA deployment (3 diego cells)
- Deploy an app with 3 instances 
- run helm upgrade to bring the count of deigo cell to 4

**Expected behavior**
A new diego cell should appear, no pods should restart.

**What happens**
some of the old diego-cell pods (2 out of 3) get restarted

**Environment**

 kubecf-2.0-RC1                  2.0-RC1 
cf-operator-4.5.6+0.gffc6f942   4.5.6+0.gffc6f942

**Additional context**
```
diego-cell-0                             7/7     Running     2          3h6m
diego-cell-1                             7/7     Running     2          6m57s
diego-cell-2                             7/7     Running     2          10m
diego-cell-3                             7/7     Running     2          24m
```

### PR DESCRIPTION
**Pull request by viovanov**
## Description
Configures the diego cell IG so it doesn't use unnecessary link instances or the REPLICAS env var.

## Motivation and Context
#fixes #981 

## How Has This Been Tested?
Locally scaled from 2 to 4 cells and back.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: scripts/cf-operator-delete.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
+#!/usr/bin/env bash
+source scripts/include/setup.sh
+
+require_tools kubectl helm
+
+set +e
```
Comment (viccuad) [inline scripts/cf-operator-delete.sh:6]: Nit: I would prefer to `set -e`, and use

```
if helm_ls 2>/dev/null | grep -qi cf-operator ; then
    helm_delete cf-operator --namespace cf-operator
fi
kubectl delete --ignore-not-found ns "${CF_OPERATOR_NS}"
```

and so on

**Review by viccuad — APPROVED** [review]

File: .gitignore [hunk 2]
```diff
@@ -8,6 +8,7 @@ password
 *.vmdk
 personal-setup
 .concourse/config.yaml
-
+.envrc
```
[the remark this answers is not in the document]
Comment (viovanov) [reply .gitignore:11]: @viccuad my envrc looks like this:

```
export VALUES=./dev-values.yaml
```

I do all my settings from `dev-values.yaml`. 
```

File: scripts/cf-operator-delete.sh (hunk 1 above)
Comment (viccuad) [reply scripts/cf-operator-delete.sh:6]: With the new changes, we can drop the `set +e`. I would like to do `set -e` in scripts/include/setup.sh to catch errors in the scripts in the future, but that's out of this PR.

**Review by viccuad — APPROVED** [review]

**Review by cfcontainerizationbot — APPROVED** [review]
